version: '3.8'

services:
  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_DATABASE: "A2_MLOPS"  

  api-gateway:
    image: 20i0964/mlops_a2:api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - database-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5001
      - DB_SERVICE_URL=http://database-service:5002

  auth-service:
    image: 20i0964/mlops_a2:auth-service
    ports:
      - "5001:5001"
    depends_on:
      - database-service
    environment:
      - DB_SERVICE_URL=http://database-service:5002

  database-service:
    image: 20i0964/mlops_a2:database-service
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/A2_MLOPS
  frontend:
    image: 20i0964/mlops_a2:frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway 