apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: api-gateway
          image: 20i0964/mlops_a2:api-gateway
          ports:
            - containerPort: 5000
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5001"
            - name: DB_SERVICE_URL
              value: "http://database-service:5002"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
