apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-service
          image: 20i0964/mlops_a2:auth-service
          ports:
            - containerPort: 5001
          env:
            - name: DB_SERVICE_URL
              value: "mongodb://database-service:27017/A2_MLOPS"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
